// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhD5eD_K4dNNF-xkn1pPHcJ-N_G8XqAJE',
    appId: '1:617281712367:web:e4eb410da92c023cd82b1a',
    messagingSenderId: '617281712367',
    projectId: 'chat-app-badfa',
    authDomain: 'chat-app-badfa.firebaseapp.com',
    databaseURL: 'https://chat-app-badfa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-badfa.appspot.com',
    measurementId: 'G-LMR90GPRXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbwhvIsQDOd1_8EYpnZhFWEfmiNdsxW-Y',
    appId: '1:617281712367:android:782779b99aebde72d82b1a',
    messagingSenderId: '617281712367',
    projectId: 'chat-app-badfa',
    databaseURL: 'https://chat-app-badfa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-badfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVn4oJyOhlVmNDapaGCOAHf8aLr8vNzQE',
    appId: '1:617281712367:ios:bf8867c0c5dc1e2ed82b1a',
    messagingSenderId: '617281712367',
    projectId: 'chat-app-badfa',
    databaseURL: 'https://chat-app-badfa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-badfa.appspot.com',
    androidClientId: '617281712367-p49a2j80v600n86cap8u3m459lte3muc.apps.googleusercontent.com',
    iosClientId: '617281712367-vniikaoji2ngj20rei7no8sktv5pmq0u.apps.googleusercontent.com',
    iosBundleId: 'com.example.publicChats',
  );
}
